#!/usr/bin/python

import sys
import os

total=0
num=0

for i in range(1,11):

  fname='log%d'%i
  fr=open(fname, 'r')

  for line in fr:
    if line.find('pkt size')!=-1:
      for field in line.split(' '):
        pkt_size=field
      num=num+1
      total=total+float(pkt_size)

print num/10
print total/num
