#!/usr/bin/python

import sys
import os

totalTime=0

y=1
while y <= 6:
  for i in range(1,11):
    fname='log%d'%y
    t='%d'%i
    fname=fname+t

    flag_after_pkt=0
    fr=open(fname, 'r')

    for line in fr:

      if line.find('sendRequest')!=-1:
        for field in line.split(' '):
          request_startTime = field

      if line.find('Transfer End')!=-1:
        for field in line.split(' '):
          transfer_endTime = field 

      if line.find('Server transfered')!=-1:
        j=1
        for field in line.split(' '):
          if j==3:
            pkt_no=field
          j=j+1

    totalTime=float(transfer_endTime)-float(request_startTime)+totalTime

  totalTime=totalTime/10
  bandwidth=float(pkt_no)*512/(totalTime)/1024*3

  print totalTime
  y=y+1
