# The first Simplest Case with only two vehicles
# Author: Zou Zhenhua

# ======================================================================
# common parameters
# ======================================================================
set val(chan)		Channel/WirelessChannel			;# channel type
set val(prop)		Propagation/TwoRayGround		;# radio-propagation model
set val(netif)		Phy/WirelessPhy				;# network interface type
set val(mac)		Mac/802_11				;# MAC type
set val(ifq)		Queue/DropTail/PriQueue			;# interface queue type
set val(ll)		LL					;# link layer type
set val(ant)		Antenna/OmniAntenna			;# antenna model
set val(ifqlen)		50					;# max packet in ifq
set val(MN)		2					;# number of  vehicles
set val(AP)		1					;# number of Access Point
set val(rp)		AODV					;# routing protocol
#set val(rp)             DumbAgent                  ;# routing protocol
set val(cp)		SimplestCaseTrace			;# the mobility file generated by VanetMobiSim
set val(stop)		350.0					;# simulation time
set val(nn)		[expr $val(AP)+$val(MN)]		;# number of mobilenodes & Access Point

# ======================================================================
# Main Program
# ======================================================================

# Initialize Global Variables
set ns_     [new Simulator]

$ns_ use-newtrace
set tracefd [open "| awk -f filter.awk > wireless.tr" w]
$ns_ trace-all $tracefd

# Set Up Topography Object
set topo       [new Topography]
$topo load_flatgrid 1000 1000

# Create God
create-god $val(nn)

# Configure default data rate for 802.11
Mac/802_11 set dataRate_ 11Mb
# Disable RTS/CTS
Mac/802_11 set RTSThreshold_ 3000

# Configure Node
$ns_ node-config -adhocRouting $val(rp) \
		 -llType $val(ll) \
		 -macType $val(mac) \
		 -ifqType $val(ifq) \
		 -ifqLen $val(ifqlen) \
		 -antType $val(ant) \
		 -propType $val(prop) \
		 -phyType $val(netif) \
		 -topoInstance $topo \
		 -agentTrace ON \
		 -routerTrace ON \
		 -macTrace ON \
		 -movementTrace ON \
		 -channel [new $val(chan)]
			 
# Define Vehicles & Access Point nodes
for {set i 0} {$i < $val(nn) } {incr i} {
	set node_($i) [$ns_ node]
	$node_($i) random-motion 0
	set mac_($i) [$node_($i) getMac 0]
}

$mac_(2) ap $[$mac_(2) id]

# Define Node Movement Model
puts "Loading mobility pattern..."
source $val(cp)

for {set i 0} {$i < $val(nn)} {incr i} {
    # 10 defines the node size in nam, must adjust it according to your scenario  
    # The function must be called after mobility model is defined
    $ns_ initial_node_pos $node_($i) 10
}

# ======================================================================
# global parameter input to the VCD application
# ======================================================================

set gp [new InputParameter]
$gp set hello_interval_ 0.5
$gp set request_interval_ 0.5
$gp set ack_timeout_ 0.1
$gp set transfer_start_ 5
$gp set process_time_ 0.00001
$gp set packet_size_ 512
$gp set file_size_ 100000

# ======================================================================
# Traffic Type & Simluation Time
# ======================================================================

# node AP
set udp_(2) [new Agent/UDP]
$ns_ attach-agent $node_(2) $udp_(2)

set VCD_(2) [new Application/VCDServer]
$VCD_(2) attach-agent $udp_(2)
$VCD_(2) set id_ 2

$ns_ at 1.2 "$VCD_(2) start"
$ns_ at $val(stop) "$VCD_(2) stop"

# node 0
set udp_(0) [new Agent/UDP]
$ns_ attach-agent $node_(0) $udp_(0)

set VCD_(0) [new Application/VCDClient]
$VCD_(0) attach-agent $udp_(0)
$VCD_(0) set id_ 0
$VCD_(0) set neighborid_ 1

$ns_ at 1.0 "$VCD_(0) start"
$ns_ at $val(stop) "$VCD_(0) stop"

# node 1
set udp_(1) [new Agent/UDP]
$ns_ attach-agent $node_(1) $udp_(1)

set VCD_(1) [new Application/VCDClient]
$VCD_(1) attach-agent $udp_(1)
$VCD_(1) set id_ 1
$VCD_(1) set neighborid_ 0

$ns_ at 1.1 "$VCD_(1) start"
$ns_ at $val(stop) "$VCD_(1) stop"

# ======================================================================
# global simluation time
# ======================================================================
$ns_ at $val(stop).9999 "puts \"NS EXITING...\" ; $ns_ halt"
$ns_ at $val(stop) "stop"

# ======================================================================
# exit function
# ======================================================================
proc stop {} {
    global ns_ tracefd
    $ns_ flush-trace
    close $tracefd
}

# ======================================================================
# start
# ======================================================================
puts "Starting Simulation..."
$ns_ run
