# The first Simplest Case with only two vehicles
# Author: Zou Zhenhua

# ======================================================================
# common parameters
# ======================================================================
set val(chan)		Channel/WirelessChannel			;# channel type
set val(prop)		Propagation/TwoRayGround		;# radio-propagation model
set val(netif)		Phy/WirelessPhyExt			;# network interface type
set val(mac)		Mac/802_11Ext     			;# MAC type
set val(ifq)		Queue/DropTail/PriQueue			;# interface queue type
set val(ll)		LL					;# link layer type
set val(ant)		Antenna/OmniAntenna			;# antenna model
set val(ifqlen)		500					;# max packet in ifq
set val(MN)		2					;# number of  vehicles
set val(AP)		1					;# number of Access Point
set val(rp)		AODV					;# routing protocol
set val(cp)		SimplestCaseTrace			;# the mobility file generated by VanetMobiSim
set val(stop)		350.0					;# simulation time
set val(nn)		[expr $val(AP)+$val(MN)]		;# number of mobilenodes & Access Point

#802.11p default parameters
Phy/WirelessPhyExt set CSThresh_                3.162e-12   ;#-85 dBm Wireless interface sensitivity (sensitivity defined in the standard)
Phy/WirelessPhyExt set Pt_                      0.001         
Phy/WirelessPhyExt set freq_                    5.9e+9
Phy/WirelessPhyExt set noise_floor_             1.26e-13    ;#-99 dBm for 10MHz bandwidth
Phy/WirelessPhyExt set L_                       1.0         ;#default radio circuit gain/loss
Phy/WirelessPhyExt set PowerMonitorThresh_      6.310e-14   ;#-102dBm power monitor  sensitivity
Phy/WirelessPhyExt set HeaderDuration_          0.000040    ;#40 us
Phy/WirelessPhyExt set BasicModulationScheme_   0
Phy/WirelessPhyExt set PreambleCaptureSwitch_   1
Phy/WirelessPhyExt set DataCaptureSwitch_       0
Phy/WirelessPhyExt set SINR_PreambleCapture_    2.5118;     ;# 4 dB
Phy/WirelessPhyExt set SINR_DataCapture_        100.0;      ;# 10 dB
Phy/WirelessPhyExt set trace_dist_              1e6         ;# PHY trace until distance of 1 Mio. km ("infinty")
Phy/WirelessPhyExt set PHY_DBG_                 0

Mac/802_11Ext set CWMin_                        15
Mac/802_11Ext set CWMax_                        1023
Mac/802_11Ext set SlotTime_                     0.000013
Mac/802_11Ext set SIFS_                         0.000032
Mac/802_11Ext set ShortRetryLimit_              7
Mac/802_11Ext set LongRetryLimit_               4
Mac/802_11Ext set HeaderDuration_               0.000040
Mac/802_11Ext set SymbolDuration_               0.000008
Mac/802_11Ext set BasicModulationScheme_        0
Mac/802_11Ext set use_802_11a_flag_             true
Mac/802_11Ext set RTSThreshold_                 2346
Mac/802_11Ext set MAC_DBG                       0

# ======================================================================
# Main Program
# ======================================================================

# Initialize Global Variables
set ns_     [new Simulator]

$ns_ use-newtrace
set tracefd [open "| awk -f filter.awk > wireless.tr" w]
#set tracefd [open /dev/null w]
#set tracefd [open wireless.tr w]
$ns_ trace-all $tracefd

set namtrace [open out.nam w]
$ns_ namtrace-all-wireless $namtrace 1000 1000

# Set Up Topography Object
set topo       [new Topography]
$topo load_flatgrid 1000 1000

# Create God
create-god $val(nn)

# Configure default data rate for 802.11
Mac/802_11 set dataRate_ 11Mb
# Disable RTS/CTS
Mac/802_11 set RTSThreshold_ 3000

# Configure Node
$ns_ node-config -adhocRouting $val(rp) \
		 -llType $val(ll) \
		 -macType $val(mac) \
		 -ifqType $val(ifq) \
		 -ifqLen $val(ifqlen) \
		 -antType $val(ant) \
		 -propType $val(prop) \
		 -phyType $val(netif) \
		 -topoInstance $topo \
		 -agentTrace OFF \
		 -routerTrace OFF \
		 -macTrace OFF \
		 -movementTrace OFF \
		 -channel [new $val(chan)]
			 
# Define Vehicles & Access Point nodes
for {set i 0} {$i < $val(nn) } {incr i} {
	set node_($i) [$ns_ node]
	$node_($i) random-motion 0
}

# Define Node Movement Model
puts "Loading mobility pattern..."
source $val(cp)

for {set i 0} {$i < $val(nn)} {incr i} {
    # 10 defines the node size in nam, must adjust it according to your scenario  
    # The function must be called after mobility model is defined
    $ns_ initial_node_pos $node_($i) 10
}

# ======================================================================
# global parameter input to the VCD application
# ======================================================================

set gp [new InputParameter]
$gp set hello_interval_ 0.5
$gp set request_interval_ 0.5
$gp set ack_timeout_ 0.1
$gp set transfer_start_ 10
$gp set process_time_ 0.00001
$gp set packet_size_ 512
$gp set file_size_ 100000

# ======================================================================
# Traffic Type & Simluation Time
# ======================================================================

# node AP
set udp_(2) [new Agent/UDP]
$ns_ attach-agent $node_(2) $udp_(2)

set VCD_(2) [new Application/VCDServer]
$VCD_(2) attach-agent $udp_(2)
$VCD_(2) set id_ 2

$ns_ at 1.2 "$VCD_(2) start"
$ns_ at $val(stop) "$VCD_(2) stop"

# node 0
set udp_(0) [new Agent/UDP]
$ns_ attach-agent $node_(0) $udp_(0)

set VCD_(0) [new Application/VCDClient]
$VCD_(0) attach-agent $udp_(0)
$VCD_(0) set id_ 0
$VCD_(0) set neighborid_ 1

$ns_ at 1.0 "$VCD_(0) start"
$ns_ at $val(stop) "$VCD_(0) stop"

# node 1
set udp_(1) [new Agent/UDP]
$ns_ attach-agent $node_(1) $udp_(1)

set VCD_(1) [new Application/VCDClient]
$VCD_(1) attach-agent $udp_(1)
$VCD_(1) set id_ 1
$VCD_(1) set neighborid_ 0

$ns_ at 1.1 "$VCD_(1) start"
$ns_ at $val(stop) "$VCD_(1) stop"

# ======================================================================
# global simluation time
# ======================================================================
$ns_ at $val(stop).9999 "puts \"NS EXITING...\" ; $ns_ halt"
$ns_ at $val(stop) "stop"

# ======================================================================
# exit function
# ======================================================================
proc stop {} {
    global ns_ tracefd
    global namtrace
    $ns_ flush-trace
    close $tracefd
    close $namtrace
}

# ======================================================================
# start
# ======================================================================
puts "Starting Simulation..."
$ns_ run